/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { EstimateProject } from '../types/xactimate';
import { unpackEsxArchive } from '../services/esxArchive';
import { generateProposalPdf } from '../services/pdfReportGenerator';
import { generateProductionChecklistPdf, buildChecklistValues } from '../services/productionChecklistPdf';
import { CHECKLIST_COLUMNS, CHECKLIST_ROWS, CHECKLIST_SECTIONS } from '../services/productionChecklistTemplate';
import { GoogleAppsScriptService } from '../services/googleAppsScriptService';
import {
  Upload,
  FileCheck2,
  Download,
  Printer,
  Calendar,
  Layers,
  FileText,
  DollarSign,
  Building2,
  ChevronRight,
} from 'lucide-react';

interface EsxToPdfViewProps {
  project: EstimateProject;
  onProjectChange: (project: EstimateProject) => void;
  onNavigateToSchedule: () => void;
}

/**
 * Document modes. The production checklist is a distinct printed form (the
 * Hays+Sons production form), not a variant of the narrative proposal, so it is
 * generated by its own template-exact service.
 */
type DocumentMode = 'PROPOSAL' | 'WORK_ORDER' | 'AUDIT_REPORT' | 'PRODUCTION_CHECKLIST';

export const EsxToPdfView: React.FC<EsxToPdfViewProps> = ({
  project,
  onProjectChange,
  onNavigateToSchedule,
}) => {
  const [docMode, setDocMode] = useState<DocumentMode>('PROPOSAL');
  const [isUnpacking, setIsUnpacking] = useState(false);
  const [unpackNotice, setUnpackNotice] = useState<string | null>(null);
  const [archiveFiles, setArchiveFiles] = useState<string[]>(['project_data.xml', 'manifest.meta', 'profile.cfg']);

  // Handle uploading of .esx file
  const handleEsxUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsUnpacking(true);
    setUnpackNotice(null);
    try {
      const { project: parsedProject, filenames } = await unpackEsxArchive(file);
      onProjectChange(parsedProject);
      setArchiveFiles(filenames);
      setUnpackNotice(
        `Successfully unpacked PKZIP archive '${file.name}'. Found ${filenames.length} container assets and parsed ${parsedProject.lineItems.length} line items.`
      );

      // Audit log
      GoogleAppsScriptService.addAuditLog({
        action: 'IMPORT',
        description: `Unpacked ESX archive: ${file.name}`,
        details: `Claim ${parsedProject.claim.claimNumber} · Insured: ${parsedProject.insured.name}`,
        status: 'SUCCESS',
      });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      alert(`ESX Unpacking Error: ${message}`);
    } finally {
      setIsUnpacking(false);
    }
  };

  // Download PDF
  const handleDownloadPdf = () => {
    if (docMode === 'PRODUCTION_CHECKLIST') {
      const doc = generateProductionChecklistPdf(project);
      doc.save(`HAYS_SONS_PRODUCTION_CHECKLIST_${project.claim.claimNumber || 'CLAIM'}.pdf`);
      return;
    }
    const doc = generateProposalPdf(project, docMode);
    const filename = `HAYS_SONS_${docMode}_${project.claim.claimNumber || 'CLAIM'}.pdf`;
    doc.save(filename);
  };

  const totalRoofSq = project.roofFacets.reduce((acc, f) => acc + f.surfaceArea, 0) / 100;
  const totalEave = project.roofFacets.reduce((acc, f) => acc + f.linearEave, 0);

  return (
    <div className="space-y-6">
      {/* Top Banner / Ingestion */}
      <div className="bg-white border border-slate-200 rounded-lg p-6 shadow-xs">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          <div>
            <div className="flex items-center gap-2 text-xs text-slate-500 mb-1">
              <span>Workflow 2</span>
              <span aria-hidden="true">·</span>
              <span>ESX Extraction</span>
              <span aria-hidden="true">·</span>
              <span>Document Generation</span>
            </div>
            <h1 className="text-xl font-bold text-slate-900 tracking-tight">
              Xactimate ESX to PDF Proposal & Report Engine
            </h1>
            <p className="text-sm text-slate-600 mt-1 max-w-2xl">
              Upload any compiled Verisk Xactimate <code className="text-red-700 bg-red-50 px-1 py-0.5 rounded text-xs font-mono">.esx</code> archive to unpack internal payloads, map relational sketch geometry, and format high-fidelity narrative proposals.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleDownloadPdf}
              className="flex items-center gap-2 px-4 py-2 text-xs font-semibold text-white bg-red-600 hover:bg-red-700 rounded-md transition shadow-xs cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Printable PDF</span>
            </button>
            <button
              onClick={onNavigateToSchedule}
              className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-slate-700 hover:text-slate-900 bg-slate-100 hover:bg-slate-200 rounded border border-slate-200 transition cursor-pointer"
            >
              <Calendar className="w-3.5 h-3.5" />
              <span>Restoration Schedule</span>
            </button>
          </div>
        </div>

        {/* ESX Upload Dropzone */}
        <div className="mt-5 border-2 border-dashed border-slate-200 hover:border-red-400 bg-slate-50 rounded-lg p-5 text-center transition">
          <input
            type="file"
            id="esx-upload-input"
            accept=".esx,.zip"
            onChange={handleEsxUpload}
            className="hidden"
          />
          <label
            htmlFor="esx-upload-input"
            className="cursor-pointer flex flex-col items-center justify-center gap-2"
          >
            <Upload className={`w-8 h-8 ${isUnpacking ? 'text-red-600 animate-bounce' : 'text-slate-400'}`} />
            <div className="text-sm font-semibold text-slate-800">
              {isUnpacking ? 'Unpacking PKZIP container and traversing XML tree...' : 'Drop Verisk .esx Archive Here to Unpack'}
            </div>
            <p className="text-xs text-slate-500">
              Reads PKZIP compressed containers, verifies manifest checksum, and extracts project_data.xml.
            </p>
          </label>
        </div>

        {/* Unpack notice */}
        {unpackNotice && (
          <div className="mt-4 p-3 bg-emerald-50 border border-emerald-200 rounded-md flex items-center justify-between text-xs text-emerald-800">
            <div className="flex items-center gap-2">
              <FileCheck2 className="w-4 h-4 text-emerald-600 shrink-0" />
              <span>{unpackNotice}</span>
            </div>
            <span className="font-mono text-[11px] text-emerald-700">
              Files: [{archiveFiles.join(', ')}]
            </span>
          </div>
        )}
      </div>

      {/* Mode Selector Tabs */}
      <div className="flex items-center justify-between bg-white border border-slate-200 rounded-lg p-2 shadow-xs">
        <div className="flex items-center gap-1">
          <button
            onClick={() => setDocMode('PROPOSAL')}
            className={`px-3 py-1.5 text-xs font-semibold rounded cursor-pointer transition ${
              docMode === 'PROPOSAL'
                ? 'bg-slate-900 text-white'
                : 'text-slate-600 hover:text-slate-900 bg-transparent'
            }`}
          >
            Client Narrative Proposal
          </button>
          <button
            onClick={() => setDocMode('WORK_ORDER')}
            className={`px-3 py-1.5 text-xs font-semibold rounded cursor-pointer transition ${
              docMode === 'WORK_ORDER'
                ? 'bg-slate-900 text-white'
                : 'text-slate-600 hover:text-slate-900 bg-transparent'
            }`}
          >
            Subcontractor Work Order
          </button>
          <button
            onClick={() => setDocMode('AUDIT_REPORT')}
            className={`px-3 py-1.5 text-xs font-semibold rounded cursor-pointer transition ${
              docMode === 'AUDIT_REPORT'
                ? 'bg-slate-900 text-white'
                : 'text-slate-600 hover:text-slate-900 bg-transparent'
            }`}
          >
            Carrier Compliance Audit
          </button>
          <button
            onClick={() => setDocMode('PRODUCTION_CHECKLIST')}
            className={`px-3 py-1.5 text-xs font-semibold rounded cursor-pointer transition ${
              docMode === 'PRODUCTION_CHECKLIST'
                ? 'bg-slate-900 text-white'
                : 'text-slate-600 hover:text-slate-900 bg-transparent'
            }`}
          >
            Production Checklist
          </button>
        </div>

        <div className="flex items-center gap-2 text-xs text-slate-500">
          <span>Claim: <strong className="text-slate-900 font-mono">{project.claim.claimNumber}</strong></span>
          <span aria-hidden="true">·</span>
          <span>RCV Total: <strong className="text-red-600 font-mono tabular-nums">${project.totals.rcvTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</strong></span>
        </div>
      </div>

      {/* Print-Ready Document Preview Surface */}
      {docMode === 'PRODUCTION_CHECKLIST' ? (
        <ProductionChecklistPreview project={project} />
      ) : (
      <div className="bg-white border border-slate-200 rounded-lg p-8 shadow-sm max-w-4xl mx-auto space-y-6 print:p-0 print:border-none">
        {/* Document Header */}
        <div className="flex items-start justify-between border-b border-slate-200 pb-6">
          <div className="flex items-center gap-3">
            {/* H+ Logo mark */}
            <svg width="48" height="32" viewBox="0 0 65 42" fill="none">
              <rect x="0" y="0" width="14" height="42" fill="#DC2626" />
              <rect x="14" y="14" width="51" height="14" fill="#1A1A1A" />
              <rect x="36" y="0" width="14" height="42" fill="#1A1A1A" />
            </svg>
            <div>
              <h2 className="text-lg font-bold text-slate-900 leading-none">Hays+Sons</h2>
              <span className="text-xs text-slate-500">Restoration Document Suite</span>
            </div>
          </div>

          <div className="text-right">
            <span className="text-xs font-bold text-red-600 uppercase tracking-wider block">
              {docMode === 'PROPOSAL'
                ? 'Scope of Repair Proposal'
                : docMode === 'WORK_ORDER'
                ? 'Subcontractor Operational Work Order'
                : docMode === 'AUDIT_REPORT'
                ? 'Xactimate ESX Audit Report'
                : 'Production Checklist'}
            </span>
            <span className="text-xs text-slate-500">
              Profile: <span className="font-mono font-semibold text-slate-800">{project.claim.profile}</span> · Date: {new Date().toLocaleDateString()}
            </span>
          </div>
        </div>

        {/* Claim & Insured Summary Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-4 bg-slate-50 border border-slate-200 rounded-md text-xs">
          <div>
            <h4 className="font-bold text-slate-900 mb-1">Claim & Policy</h4>
            <div className="space-y-0.5 text-slate-600">
              <p>Claim #: <span className="font-mono font-semibold text-slate-800">{project.claim.claimNumber}</span></p>
              <p>Policy #: <span className="font-mono text-slate-800">{project.claim.policyNumber}</span></p>
              <p>Loss: {project.claim.typeOfLoss}</p>
              <p>Price List: {project.claim.priceList}</p>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-slate-900 mb-1">Insured & Property</h4>
            <div className="space-y-0.5 text-slate-600">
              <p className="font-semibold text-slate-800">{project.insured.name}</p>
              <p>{project.insured.propertyAddress}</p>
              <p>{project.insured.city}, {project.insured.state} {project.insured.zip}</p>
              <p>Phone: {project.insured.phone || 'On file'}</p>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-slate-900 mb-1">Spatial Geometry</h4>
            <div className="space-y-0.5 text-slate-600">
              <p>Roof Pitch: <span className="font-mono text-slate-800">{project.roofFacets[0]?.pitch || '6/12'}</span></p>
              <p>Roof Surface: <span className="font-mono tabular-nums text-slate-800">{totalRoofSq.toFixed(1)} SQ</span> ({totalRoofSq > 0 ? (totalRoofSq * 100).toFixed(0) : 0} SF)</p>
              <p>Linear Eave: <span className="font-mono tabular-nums text-slate-800">{totalEave} LF</span></p>
              <p>Rooms: {project.rooms.length} interior zones</p>
            </div>
          </div>
        </div>

        {/* Line Items Table */}
        <div className="border border-slate-200 rounded-md overflow-hidden">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-900 text-white font-semibold">
              <tr>
                <th className="py-2.5 px-3 w-10">#</th>
                <th className="py-2.5 px-3 w-24">Cat/Sel</th>
                <th className="py-2.5 px-3">Description & Adjuster Justification</th>
                <th className="py-2.5 px-3 w-20 text-right">Qty</th>
                <th className="py-2.5 px-3 w-16">Unit</th>
                <th className="py-2.5 px-3 w-24 text-right">Unit Price</th>
                <th className="py-2.5 px-3 w-28 text-right">RCV Total</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {project.lineItems.map((item, idx) => (
                <tr key={item.id} className={idx % 2 === 1 ? 'bg-slate-50' : 'bg-white'}>
                  <td className="py-2.5 px-3 text-slate-400 font-mono">{idx + 1}</td>
                  <td className="py-2.5 px-3 font-mono font-bold text-slate-900">
                    {item.category} {item.selector}
                  </td>
                  <td className="py-2.5 px-3">
                    <p className="text-slate-800 font-medium">{item.description}</p>
                    {item.f9Note && (
                      <p className="text-[11px] text-red-700 italic mt-0.5">
                        <strong className="not-italic">F9 Note:</strong> {item.f9Note}
                      </p>
                    )}
                  </td>
                  <td className="py-2.5 px-3 text-right font-mono tabular-nums text-slate-700">
                    {item.quantity.toFixed(2)}
                  </td>
                  <td className="py-2.5 px-3 font-mono uppercase text-slate-600">
                    {item.unit}
                  </td>
                  <td className="py-2.5 px-3 text-right font-mono tabular-nums text-slate-700">
                    ${item.unitPrice.toFixed(2)}
                  </td>
                  <td className="py-2.5 px-3 text-right font-mono font-bold tabular-nums text-slate-900">
                    ${(item.rcv || item.total).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Financial Recap Table */}
        <div className="flex justify-end">
          <div className="w-72 bg-slate-50 border border-slate-200 rounded-md p-4 space-y-2 text-xs">
            <div className="flex justify-between text-slate-600">
              <span>Scope Subtotal:</span>
              <span className="font-mono tabular-nums">${project.totals.lineItemTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between text-slate-600">
              <span>Material Sales Tax:</span>
              <span className="font-mono tabular-nums">${project.totals.taxTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between text-slate-600">
              <span>Overhead & Profit (10/10):</span>
              <span className="font-mono tabular-nums">${(project.totals.overheadTotal + project.totals.profitTotal).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between text-slate-900 font-bold border-t border-slate-200 pt-2">
              <span>Replacement Cost (RCV):</span>
              <span className="font-mono tabular-nums text-red-600">${project.totals.rcvTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between text-slate-500">
              <span>Less Depreciation:</span>
              <span className="font-mono tabular-nums">-${project.totals.depreciationTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between text-slate-800 font-medium">
              <span>Actual Cash Value (ACV):</span>
              <span className="font-mono tabular-nums">${project.totals.acvTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between text-slate-500">
              <span>Less Deductible:</span>
              <span className="font-mono tabular-nums">-${project.totals.deductible.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between text-red-700 font-bold border-t border-slate-200 pt-2 text-sm">
              <span>Net Claim Settlement:</span>
              <span className="font-mono tabular-nums">${project.totals.netClaim.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </div>
          </div>
        </div>

        {/* Authorizations and Certification */}
        <div className="pt-6 border-t border-slate-200 grid grid-cols-1 sm:grid-cols-2 gap-8 text-xs text-slate-500">
          <div>
            <span className="block font-semibold text-slate-700 mb-1">Restoration Estimator Certification:</span>
            <p className="mb-4">This scope reflects structural damage inspected and verified in accordance with IICRC and Haag standards.</p>
            <div className="border-b border-slate-300 w-48 mb-1"></div>
            <p className="font-semibold text-slate-800">{project.estimator.name}</p>
            <p>{project.estimator.company}</p>
          </div>

          <div>
            <span className="block font-semibold text-slate-700 mb-1">Insured Policyholder Acceptance:</span>
            <p className="mb-4">I authorize Hays + Sons Complete Restoration to execute the itemized scope above per policy provisions.</p>
            <div className="border-b border-slate-300 w-48 mb-1"></div>
            <p className="font-semibold text-slate-800">{project.insured.name}</p>
            <p>Date: ________________________</p>
          </div>
        </div>
      </div>
      )}
    </div>
  );
};

/**
 * On-screen summary of the Production Checklist.
 *
 * The download is the authoritative artefact: it reproduces the printed
 * Hays+Sons production form. This panel shows which job values are typed onto
 * the form's fill lines, and flags the fields that stay blank because the app
 * does not hold them yet.
 */
const ProductionChecklistPreview: React.FC<{ project: EstimateProject }> = ({ project }) => {
  const values = buildChecklistValues(project);
  const rows = Object.entries(values) as [keyof typeof values, string][];
  const filled = rows.filter(([, value]) => value);
  const blank = rows.filter(([, value]) => !value);

  return (
    <div className="bg-white border border-slate-200 rounded-lg p-8 shadow-sm max-w-4xl mx-auto space-y-6 print:p-0 print:border-none">
      <div className="flex items-start justify-between border-b border-slate-200 pb-6">
        <div className="flex items-center gap-3">
          <svg width="48" height="32" viewBox="0 0 65 42" fill="none">
            <rect x="0" y="0" width="14" height="42" fill="#DC2626" />
            <rect x="14" y="14" width="51" height="14" fill="#1A1A1A" />
            <rect x="36" y="0" width="14" height="42" fill="#1A1A1A" />
          </svg>
          <div>
            <h2 className="text-lg font-bold text-slate-900 leading-none">Hays+Sons</h2>
            <span className="text-xs text-slate-500">Restoration Document Suite</span>
          </div>
        </div>
        <div className="text-right">
          <span className="text-xs font-bold text-red-600 uppercase tracking-wider block">
            Production Checklist
          </span>
          <span className="text-xs text-slate-500">
            Claim: <span className="font-mono font-semibold text-slate-800">{project.claim.claimNumber}</span>
          </span>
        </div>
      </div>

      <div className="text-xs text-slate-600">
        <p className="font-semibold text-slate-900 mb-1">
          Printed form: {CHECKLIST_SECTIONS.length} sections,{' '}
          {CHECKLIST_COLUMNS.reduce((n, column) => n + Math.max(0, column.edges.length - 1), 0)} checkbox
          boxes, {CHECKLIST_ROWS.reduce((n, row) => n + (row.rules?.length ?? 0), 0)} fill lines
        </p>
        <p>
          Homeowner Information · Estimates and Required Documentation · IPC Requirements · Agent/Adjuster
          Information · Claim/Check Information — reproduced 1:1 from the Hays+Sons production form, with the
          values below typed onto its lines.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
        <div className="border border-slate-200 rounded-md overflow-hidden">
          <div className="bg-slate-900 text-white font-semibold px-3 py-2">Captured from this claim</div>
          <table className="w-full">
            <tbody className="divide-y divide-slate-100">
              {filled.map(([key, value]) => (
                <tr key={key}>
                  <td className="px-3 py-1.5 text-slate-500 font-mono">{key}</td>
                  <td className="px-3 py-1.5 text-slate-900 font-medium text-right">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="border border-slate-200 rounded-md overflow-hidden">
          <div className="bg-slate-100 text-slate-700 font-semibold px-3 py-2">
            Printed blank (not held by the estimate import)
          </div>
          <div className="p-3 flex flex-wrap gap-1.5">
            {blank.map(([key]) => (
              <span key={key} className="px-2 py-0.5 rounded bg-slate-50 border border-slate-200 text-slate-500 font-mono">
                {key}
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
